export const DARIJA_PHONETIC_MAP: Record<string, string> = {
  'salam': 'السّلامُ',
  'sba7 l-khir': 'صْباح الخير',
  'msa l-khir': 'مْسا الخير',
  'labas': 'لاباس',
  'kif dayer': 'كيف داير',
  'kif dayra': 'كيف دايرة',
  'hamdullah': 'الحمد لله',
  'shukran': 'شُكراً',
  '3afak': 'عافاك',
  'afak': 'عافاك',
  'smahli': 'سمح لي',
  'bessaha': 'بالصّحّة',
  'lahetek saha': 'الله يعطيك الصّحّة',
  'tbarkellah': 'تبارك الله',
  'bslama': 'بْسْلامة',
  'merhba': 'مْرحبا',
  'wakha': 'واخّا',
  'iyeh': 'إييه',
  'lla': 'لّا',
  'hchouma': 'حشومة',
  'mashi moshkil': 'ماشي مُشكل',
  'atay': 'أتاي',
  '9hwa': 'قْهوة',
  '9hwa nss-nss': 'قْهوة نص نص',
  'lma': 'لما',
  'lma skhoun': 'لما سخون',
  'lma bared': 'لما بارد',
  '3asir': 'عصير',
  'khobz': 'خْبز',
  'sukkar': 'سُكّر',
  'bla sekkar': 'بلا سكّر',
  'bghit': 'بغيت',
  'ma-bghit-ch': 'ما بغيتش',
  'l-hsab': 'لحساب',
  'ftour': 'فطور',
  'ghdha': 'غدا',
  '3sha': 'عشا',
  'tajine': 'طاجين',
  'zit zitoun': 'زيت زيتون',
  'm3elqa': 'معلقة',
  'farshita': 'فرشيطة',
  'korsa': 'كرصة',
  'khdem l-kuntur': 'خدم لكونتور',
  'dor 3la limen': 'دور على ليمن',
  'dor 3la lisir': 'دور على ليسير',
  'sir nishan': 'سير نيشان',
  'wqef hna': 'وقف هنا',
  'l-ma7etta': 'لمحطّة',
  'l-matar': 'لمطار',
  'bab': 'باب',
  'zanqa': 'زنقة',
  'medina qdima': 'مدينة قديمة',
  'qrib': 'قريب',
  'b3id': 'بعيد',
  'fin ghadi': 'فين غادي',
  'wsel-na': 'وصلنا',
  'sh7al hada': 'شحال هادا',
  'ghali bzzaf': 'غالي بزّاف',
  'nqess shwiya': 'نقص شويّة',
  'flus': 'فلوس',
  'sarf': 'صرف',
  'akher taman': 'آخر ثمن',
  'zwin': 'زوين',
  'zwina': 'زوينة',
  'kbir': 'كبير',
  'sghir': 'صغير',
  'zerbiya': 'زربيّة',
  'belgha': 'بلغة',
  'jellaba': 'جلابة',
  'chri-t': 'شريت',
  'baraka': 'باراكا',
  'dar': 'دار',
  'riad': 'رياض',
  'bit': 'بيت',
  'sarout': 'ساروت',
  'l-kra': 'لكرا',
  'dman': 'ضمان',
  'moul d-dar': 'مول الدار',
  'l-berd': 'لبرد',
  's-skhona': 'السخونة',
  's-stah': 'السطح',
  'l-moushkil': 'المشكل',
  'kheddam': 'خدّام',
  'khaser': 'خاسر',
  'nqi': 'نقي',
  'moussek': 'موسّخ',
  'farmasiyan': 'فرماسيان',
  'tbib': 'طبيب',
  'sbitar': 'صبيطار',
  '3awenni': 'عاوني',
  'd-dwa': 'الدوا',
  'darni rasi': 'ضرني راسي',
  'l-krash': 'الكرش',
  'bolis': 'بوليس',
  'daba': 'دابا',
  'ghedda': 'غدّا',
  'l-bare7': 'لبارح',
  'shwiya': 'شويّة',
  'bzzaf': 'بزّاف',
  'waqt': 'وقت',
  'mzyan': 'مزيان',
  'chkun': 'شكون',
  'fin': 'فين',
  'chaf': 'شاف',
  'choft': 'شفت',
  'gal': 'گال',
  'guelt': 'گلت',
  'mcha': 'مشى',
  'mchit': 'مشيت',
  'lli fat mat': 'لّي فات مات',
  'drba b drba kat-bna d-dar': 'دربا ب دربا كتبنى الدار',
  'zrbat matat': 'زربات ماتت'
};

export function normalizeDarija(text: string, arabicText?: string): string {
  if (arabicText && arabicText.trim()) return arabicText;
  const cleanKey = text.toLowerCase().trim().replace(/['"-]/g, '');
  if (DARIJA_PHONETIC_MAP[cleanKey]) {
    return DARIJA_PHONETIC_MAP[cleanKey];
  }
  // Conversion caractère par caractère si hors dictionnaire
  return text
    .replace(/3/g, 'ع')
    .replace(/7/g, 'ح')
    .replace(/9/g, 'ق')
    .replace(/kh/gi, 'خ')
    .replace(/gh/gi, 'غ');
}
