#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Expand paywall/install/passport translation keys in all 4 languages."""
import io

PATH = "src/lib/i18n/translations.ts"
with io.open(PATH, encoding="utf-8") as f:
    lines = f.readlines()

def L(s):
    return s + "\n"

fr_paywall = '      paywall: { errorInit: "Erreur lors de l\'initialisation du paiement", upgradeSuccess: "Compte mis à niveau avec succès vers Kenza Pro (Mode Démo) !", errorRetry: "Impossible d\'initialiser le paiement. Veuillez réessayer.", closeLabel: "Fermer la modale", advancedPath: "PARCOURS AVANCÉ", unlockB1B2: "Débloquez les Modules B1 & B2", advancedDesc: "Poursuivez votre voyage vers Tanger et approfondissez les subtilités du dialecte marocain.", aiImmersion: "IMMERSION IA SANS LIMITE", unlimitedAi: "Conversations IA Illimitées", aiSubtitle: "Vous avez terminé votre session IA gratuite du jour. Passez à Kenza Pro pour échanger librement avec tous les personas.", culturalKicker: "PASSEPORT CULTUREL", masterDarija: "Maîtrisez la Darija sans limites", culturalSubtitle: "Libérez tout le potentiel de votre apprentissage de la Darija avec l\'accès complet à l\'écosystème Kenza.", benefit1: "Accès intégral aux Modules 3, 4 et 5 (Niveaux B1 & B2)", benefit2: "Roleplay IA illimité (Tous les personas et scénarios sans quota)", benefit3: "Synthèse vocale (TTS) naturelle & mode 100% hors-ligne", benefit4: "Visas officiels du Passeport Culturel & suivi de maîtrise", certified: "Apprentissage certifié — Garanti sans engagement", plansTitle: "Formules Kenza Pro", chooseCadence: "Choisissez votre cadence", cadenceDesc: "Investissez dans votre aisance orale. Modifiable à tout instant.", bestOffer: "-40% · Meilleure offre", yearly: "Abonnement Annuel", billed: "Facturé {total}", perMonth: "/ mois", monthly: "Abonnement Mensuel", monthlyDesc: "Liberté totale, sans engagement", preparing: "Préparation du paiement...", unlockCta: "Débloquer Kenza Pro", securePayment: "Paiement chiffré et sécurisé · Annulation en 1 clic à tout moment." },'
fr_install = '      install: { title: "Installer KENZA", iosHintA: "Touchez l\'icône", iosHintB: "puis « Sur l\'écran d\'accueil » pour un accès rapide.", androidHint: "Ajoutez l\'app sur votre écran d\'accueil pour une expérience optimale.", button: "Installer l\'application" },'
fr_passport = '      passport: { title: "Mon Passeport Darija", guest: "INVITÉ(E)", copied: "Copié !", shareText: "J\'ai validé mon {level} de Darija marocaine sur KENZA avec un score de {score}% !", passportTitle: "PASSEPORT DARIJA", holder: "Titulaire", levelValidated: "Niveau Validé", score: "SCORE", validated: "VALIDÉ", save: "Enregistrer", share: "Partager" }'

en_paywall = '      paywall: { errorInit: "Error initializing payment", upgradeSuccess: "Account upgraded to Kenza Pro (Demo Mode)!", errorRetry: "Could not initialize payment. Please try again.", closeLabel: "Close dialog", advancedPath: "ADVANCED PATH", unlockB1B2: "Unlock Modules B1 & B2", advancedDesc: "Continue your journey to Tangier and deepen your grasp of the Moroccan dialect.", aiImmersion: "UNLIMITED AI IMMERSION", unlimitedAi: "Unlimited AI Conversations", aiSubtitle: "You have used your free AI session for today. Go Kenza Pro to chat freely with all personas.", culturalKicker: "CULTURAL PASSPORT", masterDarija: "Master Darija without limits", culturalSubtitle: "Unlock the full potential of your Darija learning with complete access to the Kenza ecosystem.", benefit1: "Full access to Modules 3, 4 and 5 (Levels B1 & B2)", benefit2: "Unlimited AI roleplay (All personas and scenarios, no quota)", benefit3: "Natural text-to-speech (TTS) & 100% offline mode", benefit4: "Official Cultural Passport visas & mastery tracking", certified: "Certified learning — Guaranteed no commitment", plansTitle: "Kenza Pro plans", chooseCadence: "Choose your pace", cadenceDesc: "Invest in your speaking confidence. Change anytime.", bestOffer: "-40% · Best offer", yearly: "Yearly Plan", billed: "Billed {total}", perMonth: "/ month", monthly: "Monthly Plan", monthlyDesc: "Total freedom, no commitment", preparing: "Preparing payment...", unlockCta: "Unlock Kenza Pro", securePayment: "Encrypted and secure payment · Cancel in 1 click anytime." },'
en_install = '      install: { title: "Install KENZA", iosHintA: "Tap the share icon", iosHintB: "then \\"Add to Home Screen\\" for quick access.", androidHint: "Add the app to your home screen for the best experience.", button: "Install the app" },'
en_passport = '      passport: { title: "My Darija Passport", guest: "GUEST", copied: "Copied!", shareText: "I passed my {level} of Moroccan Darija on KENZA with a score of {score}%!", passportTitle: "DARIJA PASSPORT", holder: "Holder", levelValidated: "Level Passed", score: "SCORE", validated: "VALIDATED", save: "Save", share: "Share" }'

es_paywall = '      paywall: { errorInit: "Error al inicializar el pago", upgradeSuccess: "¡Cuenta actualizada a Kenza Pro (Modo Demo)!", errorRetry: "No se pudo inicializar el pago. Inténtalo de nuevo.", closeLabel: "Cerrar ventana", advancedPath: "RUTA AVANZADA", unlockB1B2: "Desbloquea los Módulos B1 y B2", advancedDesc: "Continúa tu viaje hacia Tánger y profundiza en las sutilezas del dialecto marroquí.", aiImmersion: "INMERSIÓN IA SIN LÍMITE", unlimitedAi: "Conversaciones IA Ilimitadas", aiSubtitle: "Has agotado tu sesión de IA gratuita de hoy. Pasa a Kenza Pro para conversar libremente con todos los personajes.", culturalKicker: "PASAPORTE CULTURAL", masterDarija: "Domina la Darija sin límites", culturalSubtitle: "Libera todo el potencial de tu aprendizaje de Darija con acceso completo al ecosistema Kenza.", benefit1: "Acceso total a los Módulos 3, 4 y 5 (Niveles B1 y B2)", benefit2: "Roleplay IA ilimitado (Todos los personajes y escenarios sin cuota)", benefit3: "Voz sintetizada (TTS) natural y modo 100% sin conexión", benefit4: "Visados oficiales del Pasaporte Cultural y seguimiento de dominio", certified: "Aprendizaje certificado — Garantizado sin compromiso", plansTitle: "Planes Kenza Pro", chooseCadence: "Elige tu ritmo", cadenceDesc: "Invierte en tu fluidez oral. Modificable en cualquier momento.", bestOffer: "-40% · Mejor oferta", yearly: "Plan Anual", billed: "Facturado {total}", perMonth: "/ mes", monthly: "Plan Mensual", monthlyDesc: "Libertad total, sin compromiso", preparing: "Preparando el pago...", unlockCta: "Desbloquear Kenza Pro", securePayment: "Pago cifrado y seguro · Cancela en 1 clic cuando quieras." },'
es_install = '      install: { title: "Instalar KENZA", iosHintA: "Toca el icono de compartir", iosHintB: "y luego «Añadir a pantalla de inicio» para un acceso rápido.", androidHint: "Añade la app a tu pantalla de inicio para una experiencia óptima.", button: "Instalar la aplicación" },'
es_passport = '      passport: { title: "Mi Pasaporte Darija", guest: "INVITADO(A)", copied: "¡Copiado!", shareText: "¡Aprobé mi {level} de Darija marroquí en KENZA con una puntuación del {score}%!", passportTitle: "PASAPORTE DARIJA", holder: "Titular", levelValidated: "Nivel Aprobado", score: "PUNTOS", validated: "VALIDADO", save: "Guardar", share: "Compartir" }'

ar_paywall = '      paywall: { errorInit: "خطأ في تهيئة الدفع", upgradeSuccess: "تمت ترقية الحساب بنجاح إلى كنزة برو (وضع تجريبي)!", errorRetry: "تعذّر تهيئة الدفع. يرجى المحاولة مرة أخرى.", closeLabel: "إغلاق النافذة", advancedPath: "المسار المتقدم", unlockB1B2: "افتح الوحدتين B1 و B2", advancedDesc: "واصل رحلتك نحو طنجة وتعمّق في دقائق اللهجة المغربية.", aiImmersion: "انغماس ذكاء اصطناعي بلا حدود", unlimitedAi: "محادثات ذكاء اصطناعي غير محدودة", aiSubtitle: "لقد أنهيت جلسة الذكاء الاصطناعي المجانية لهذا اليوم. انتقل إلى كنزة برو للتحاور بحرية مع جميع الشخصيات.", culturalKicker: "جواز السفر الثقافي", masterDarija: "أتقن الدارجة بلا حدود", culturalSubtitle: "أطلق كامل إمكانات تعلّمك للدارجة مع الوصول الكامل إلى منظومة كنزة.", benefit1: "وصول كامل إلى الوحدات 3 و4 و5 (المستويان B1 و B2)", benefit2: "لعب أدوار بالذكاء الاصطناعي بلا حدود (كل الشخصيات والمشاهد دون حصة)", benefit3: "تركيب صوتي طبيعي (TTS) ووضع يعمل 100% دون اتصال", benefit4: "تأشيرات رسمية لجواز السفر الثقافي وتتبّع الإتقان", certified: "تعلّم موثّق — مضمون دون التزام", plansTitle: "خطط كنزة برو", chooseCadence: "اختر وتيرتك", cadenceDesc: "استثمر في طلاقتك الشفهية. قابلة للتغيير في أي وقت.", bestOffer: "-40% · أفضل عرض", yearly: "اشتراك سنوي", billed: "يُفوتَر {total}", perMonth: "/ شهر", monthly: "اشتراك شهري", monthlyDesc: "حرية كاملة، دون التزام", preparing: "جارٍ تحضير الدفع...", unlockCta: "افتح كنزة برو", securePayment: "دفع مشفّر وآمن · إلغاء بنقرة واحدة في أي وقت." },'
ar_install = '      install: { title: "ثبّت كَنزة", iosHintA: "اضغط على أيقونة المشاركة", iosHintB: "ثم «إضافة إلى الشاشة الرئيسية» للوصول السريع.", androidHint: "أضف التطبيق إلى شاشتك الرئيسية لتجربة مثالية.", button: "تثبيت التطبيق" },'
ar_passport = '      passport: { title: "جواز سفري للدارجة", guest: "ضيف", copied: "تم النسخ!", shareText: "اجتزت {level} في الدارجة المغربية على كَنزا بدرجة {score}%!", passportTitle: "جواز سفر الدارجة", holder: "الحامل", levelValidated: "المستوى المجتاز", score: "النقاط", validated: "مُصادَق", save: "حفظ", share: "مشاركة" }'

# 0-indexed line numbers
repl = {
    101: fr_paywall, 102: fr_install, 103: fr_passport,
    203: en_paywall, 204: en_install, 205: en_passport,
    305: es_paywall, 306: es_install, 307: es_passport,
    407: ar_paywall, 408: ar_install, 409: ar_passport,
}

for idx, val in repl.items():
    assert lines[idx].lstrip().startswith(("paywall:", "install:", "passport:")), \
        "Line %d mismatch: %r" % (idx, lines[idx][:40])
    lines[idx] = L(val)

with io.open(PATH, "w", encoding="utf-8") as f:
    f.writelines(lines)

print("translations OK - 12 lines replaced")
