-- =============================================================================
-- Rattrapage : aligne la base distante sur le dépôt (et versionne ce qui a été
-- créé à la main sur le remote).
--
-- Contexte : le CLI Supabase n'a jamais appliqué supabase/migrations. Le schéma
-- distant a été construit manuellement. Ce fichier rattrape les objets manquants
-- et documente les objets présents uniquement en distant.
--
-- Idempotent : rejouable autant de fois que nécessaire, via `supabase db push`
-- ou en le collant directement dans le SQL Editor du Dashboard.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Tables
-- -----------------------------------------------------------------------------

-- Table ajoutée par 20260928120000 mais absente en distant.
CREATE TABLE IF NOT EXISTS public.api_rate_limits (
  key TEXT PRIMARY KEY,
  count INTEGER NOT NULL DEFAULT 0,
  reset_at TIMESTAMPTZ NOT NULL
);

ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;
-- Aucune policy : accès direct refusé à anon/authenticated. Seules les RPC
-- SECURITY DEFINER ci-dessous peuvent la manipuler.

-- Table ajoutée par 0001_init_schema mais absente en distant.
CREATE TABLE IF NOT EXISTS public.user_checkpoints (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  checkpoint_id TEXT NOT NULL,
  score INTEGER NOT NULL,
  certificate_code TEXT,
  passed_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, checkpoint_id)
);

ALTER TABLE public.user_checkpoints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own checkpoints" ON public.user_checkpoints;
CREATE POLICY "Users can view own checkpoints"
  ON public.user_checkpoints FOR SELECT USING (auth.uid() = user_id);
-- Volontairement aucune policy INSERT/UPDATE : la table s'écrit uniquement via
-- public.claim_checkpoint_reward (SECURITY DEFINER), qui génère le code côté serveur.

-- -----------------------------------------------------------------------------
-- 2. Tables de suivi présentes en distant mais absentes du dépôt (versionnées ici)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.funnel_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anonymous_id TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  event_name TEXT,
  page_path TEXT,
  referrer TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_content TEXT,
  utm_term TEXT,
  properties JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.funnel_events ENABLE ROW LEVEL SECURITY;

-- L'app insère un événement aussi bien pour un visiteur anonyme que connecté.
DROP POLICY IF EXISTS "Anyone can insert funnel events" ON public.funnel_events;
CREATE POLICY "Anyone can insert funnel events"
  ON public.funnel_events FOR INSERT
  WITH CHECK (user_id IS NULL OR user_id = auth.uid());

DROP POLICY IF EXISTS "Users can view own funnel events" ON public.funnel_events;
CREATE POLICY "Users can view own funnel events"
  ON public.funnel_events FOR SELECT
  USING (user_id IS NOT NULL AND user_id = auth.uid());

CREATE INDEX IF NOT EXISTS funnel_events_created_at_idx ON public.funnel_events (created_at DESC);
CREATE INDEX IF NOT EXISTS funnel_events_event_name_idx ON public.funnel_events (event_name);
CREATE INDEX IF NOT EXISTS funnel_events_anonymous_id_idx ON public.funnel_events (anonymous_id);

CREATE TABLE IF NOT EXISTS public.user_attribution (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  anonymous_id TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_content TEXT,
  utm_term TEXT,
  referrer TEXT,
  landing_page TEXT,
  first_seen_at TIMESTAMPTZ,
  signup_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.user_attribution ENABLE ROW LEVEL SECURITY;

-- Écriture via le trigger handle_new_user et la RPC claim_attribution (OAuth),
-- tous deux SECURITY DEFINER : aucune policy INSERT/UPDATE n'est nécessaire.
DROP POLICY IF EXISTS "Users can view own attribution" ON public.user_attribution;
CREATE POLICY "Users can view own attribution"
  ON public.user_attribution FOR SELECT USING (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- 3. RPC
-- -----------------------------------------------------------------------------

-- Rate limiting durable (remplace le Map en mémoire, inopérant en serverless).
-- Fenêtre fixe atomique : incrémente si la fenêtre est valide, sinon réinitialise.
CREATE OR REPLACE FUNCTION public.check_rate_limit(
  p_key text,
  p_limit integer,
  p_window_ms bigint
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  new_count integer;
BEGIN
  INSERT INTO public.api_rate_limits (key, count, reset_at)
  VALUES (p_key, 1, now() + (p_window_ms || ' milliseconds')::interval)
  ON CONFLICT (key) DO UPDATE SET
    count = CASE
      WHEN public.api_rate_limits.reset_at > now()
      THEN public.api_rate_limits.count + 1
      ELSE 1
    END,
    reset_at = CASE
      WHEN public.api_rate_limits.reset_at > now()
      THEN public.api_rate_limits.reset_at
      ELSE now() + (p_window_ms || ' milliseconds')::interval
    END
  RETURNING count INTO new_count;

  RETURN new_count <= p_limit;
END;
$$;

CREATE OR REPLACE FUNCTION public.purge_expired_rate_limits()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  DELETE FROM public.api_rate_limits WHERE reset_at < now();
END;
$$;

-- Synchronisation de la progression (XP / streak / badges).
-- L'UPDATE direct des colonnes sensibles est révoqué plus bas : cette RPC est le
-- seul chemin d'écriture, avec vérification de delta pour bloquer la triche.
CREATE OR REPLACE FUNCTION public.sync_user_progress(
  new_xp integer,
  new_streak_days integer,
  new_streak_freezes integer,
  new_badges text[]
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  current_xp integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT xp INTO current_xp FROM public.profiles WHERE id = auth.uid();

  IF current_xp IS NULL THEN
    RAISE EXCEPTION 'Profile not found';
  END IF;

  IF new_xp < current_xp THEN
    RAISE EXCEPTION 'XP cannot decrease';
  END IF;

  IF (new_xp - current_xp) > 1000 THEN
    RAISE EXCEPTION 'Suspicious XP gain';
  END IF;

  UPDATE public.profiles
  SET
    xp = new_xp,
    streak_days = new_streak_days,
    streak_freezes = new_streak_freezes,
    unlocked_badges = new_badges,
    updated_at = now()
  WHERE id = auth.uid();
END;
$$;

-- Récompense de checkpoint : génère le code de certificat côté serveur.
-- L'ancienne surcharge (checkpoint_id, score, certificate_code) est supprimée :
-- elle laissait le client fournir lui-même son code.
DROP FUNCTION IF EXISTS public.claim_checkpoint_reward(text, integer, text);

CREATE OR REPLACE FUNCTION public.claim_checkpoint_reward(
  checkpoint_id text,
  score integer
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  lessons_completed integer;
  generated_code text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF score < 0 OR score > 100 THEN
    RAISE EXCEPTION 'Invalid score';
  END IF;

  SELECT count(*) INTO lessons_completed
  FROM public.lesson_progress
  WHERE user_id = auth.uid() AND score > 0;

  IF lessons_completed < 3 THEN
    RAISE EXCEPTION 'Prerequisites not met';
  END IF;

  generated_code := 'KZ-' || upper(substring(gen_random_uuid()::text, 1, 8));

  INSERT INTO public.user_checkpoints (user_id, checkpoint_id, score, certificate_code, passed_at)
  VALUES (auth.uid(), checkpoint_id, score, generated_code, now())
  ON CONFLICT (user_id, checkpoint_id)
  DO UPDATE SET
    score = EXCLUDED.score,
    certificate_code = EXCLUDED.certificate_code,
    passed_at = EXCLUDED.passed_at;

  RETURN generated_code;
END;
$$;

-- Rattachement de la source d'acquisition au retour d'un OAuth (Google).
-- Le paramètre est un JSON unique, ce qui correspond à l'appel
-- `supabase.rpc('claim_attribution', { p: {...} })` côté client.
CREATE OR REPLACE FUNCTION public.claim_attribution(p jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  INSERT INTO public.user_attribution (
    user_id, anonymous_id, utm_source, utm_medium, utm_campaign,
    utm_content, utm_term, referrer, landing_page, first_seen_at, signup_at
  )
  VALUES (
    auth.uid(),
    p->>'anonymous_id',
    p->>'utm_source',
    p->>'utm_medium',
    p->>'utm_campaign',
    p->>'utm_content',
    p->>'utm_term',
    p->>'referrer',
    p->>'landing_page',
    NULLIF(p->>'first_seen_at', '')::timestamptz,
    now()
  )
  ON CONFLICT (user_id) DO UPDATE SET
    anonymous_id = EXCLUDED.anonymous_id,
    utm_source = EXCLUDED.utm_source,
    utm_medium = EXCLUDED.utm_medium,
    utm_campaign = EXCLUDED.utm_campaign,
    utm_content = EXCLUDED.utm_content,
    utm_term = EXCLUDED.utm_term,
    referrer = EXCLUDED.referrer,
    landing_page = EXCLUDED.landing_page,
    first_seen_at = COALESCE(public.user_attribution.first_seen_at, EXCLUDED.first_seen_at);
END;
$$;

GRANT EXECUTE ON FUNCTION public.claim_attribution(jsonb) TO authenticated;

-- -----------------------------------------------------------------------------
-- 4. Création de profil + attribution à l'inscription
-- -----------------------------------------------------------------------------

-- Remplace la version du dépôt, qui ne capturait pas la source d'acquisition :
-- l'app transmet anonymous_id / utm_* dans les métadonnées d'inscription.
--
-- ATTENTION : cette définition écrase celle du distant. Avant d'appliquer, si le
-- trigger y a été enrichi à la main, comparer avec :
--   select pg_get_functiondef('public.handle_new_user'::regproc);
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.profiles (id, xp, streak_days, streak_freezes, unlocked_badges)
  VALUES (new.id, 0, 1, 1, '{}')
  ON CONFLICT (id) DO NOTHING;

  -- L'attribution ne doit jamais faire échouer une inscription.
  BEGIN
    INSERT INTO public.user_attribution (
      user_id, anonymous_id, utm_source, utm_medium, utm_campaign,
      utm_content, utm_term, referrer, landing_page, first_seen_at, signup_at
    )
    SELECT
      new.id,
      new.raw_user_meta_data->>'anonymous_id',
      new.raw_user_meta_data->>'utm_source',
      new.raw_user_meta_data->>'utm_medium',
      new.raw_user_meta_data->>'utm_campaign',
      new.raw_user_meta_data->>'utm_content',
      new.raw_user_meta_data->>'utm_term',
      new.raw_user_meta_data->>'referrer',
      new.raw_user_meta_data->>'landing_page',
      NULLIF(new.raw_user_meta_data->>'first_seen_at', '')::timestamptz,
      now()
    WHERE new.raw_user_meta_data ? 'anonymous_id'
    ON CONFLICT (user_id) DO NOTHING;
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- -----------------------------------------------------------------------------
-- 5. Durcissement : l'XP et les badges ne s'écrivent plus en direct
-- -----------------------------------------------------------------------------

-- Idempotent : REVOKE d'un privilège déjà révoqué est sans effet.
REVOKE UPDATE (xp, streak_days, streak_freezes, unlocked_badges)
  ON public.profiles FROM authenticated, anon;
